openapi: 3.0.3
info:
  title: Global Furniture
  version: 1.0.0
  description: |-

    Global Furniture es una empresa que se dedica a fabricar muebles a través de materiales
    sustentables y reciclados, desde madera a policarbonato o nylon reciclado. Nos enfocamos en 
    brindar siempre la mejor calidad de muebles ya sea con estilos modernos como vintage.

    _A continuación guardamos la metodología con la cual nos comunicamos con las APIS de terceros para poder lograr nuestros objetivos organizacionales_
    
servers:
  - url: {{url}}:{{port}}/api
  
tags:
  - name: auth
    description: Todo lo necesario relacionado al usuario.
  - name: materials
    description: Todo lo necesario para pedir materiales
  - name: slots
    description: Todo lo necesario para reservar slots de fabricación

paths:
  /login:
    post:
      tags:
        - auth
      summary: Iniciar sesión al servicio.
      description: Autenticar un usuario y obtener su token de acceso. Requiere `private_login` (todos los usuarios no-autenticados lo tienen).
      operationId: loginUser
      requestBody:
        description: Autenticar un usuario y obtener su token de acceso.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiam9obiBkb2UifQ.XXXXXXXXXXXXXXXXXXXXXXXXX
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Credenciales inválidas
        '403': 
          description: User doesn't have permission
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No tiene permisos

  /me/editar_perfil:
    post:
      tags:
        - auth
      summary: Cambiar la contraseña del usuario.
      description: Cambiar la contraseña del usuario autenticado. Requiere `private_profile_edit`.
      operationId: changePassword
      requestBody:
        description: Cambiar la contraseña del usuario autenticado.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPassword'
        required: true
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Password change successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Contraseña cambiada exitosamente
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Credenciales inválidas
        '403': 
          description: User doesn't have permission
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No tiene permisos


  /materials/create:
    post:
      tags:
        - materials
      summary: Agregar un nuevo material a la API de proveedores
      description: Agregar un nuevo material a la API. Requiere `material_create`.
      operationId: createMaterial
      requestBody:
        description: Agregar un nuevo material a la API
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Material'
        required: true
      responses:
        '200':
          description: Successful operation
          content:

            application/json:
              schema:
                $ref: '#/components/schemas/Material'          
        '400':
          description: Invalid input
      security:
        - bearerAuth: []

  /materials/all:
    get:
      tags:
        - materials
      summary: Lista a todos los materiales disponibles
      description: Devuelve a todos los materiales disponibles en la API. Requiere `material_all`.
      operationId: allMaterials
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Material'          
        '400':
          description: Something went wrong
        '404':
          description: Materials not found
      security:
        - bearerAuth: []
            
  /materials/getByName:  #name?
    get:
      tags:
        - materials
      summary: Busca materiales por nombre
      description: Busca materiales por nombre. Se pueden agregar varios si se utilizan comas. Requiere `material_get`.
      operationId: getByNameMaterial
      parameters:
        - name: materialName
          in: query
          description: Nombres por el cual filtrar los materiales
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Material'          
        '400':
          description: Invalid name value
        '404':
          description: Material not found
      security:
        - bearerAuth: []

  /materials/getById:
    get:
      tags:
        - materials
      summary: Busca materiales por ID
      description: Busca un unico material por su ID. Requiere `material_get`.
      operationId: getByIdMaterial
      parameters:
        - name: materialId
          in: query
          description: ID del material
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Material'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Material not found
      security:
        - bearerAuth: []



  /slots/create:
    post:
      tags:
        - slots
      summary: Agregar un nuevo slot a la API de proveedores
      description: Agregar un nuevo slot a la API. Requiere `slot_create`.
      operationId: createSlots
      requestBody:
        description: Agregar un nuevo slot a la API
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Slot'
        required: true
      responses:
        '200':
          description: Successful operation
          content:

            application/json:
              schema:
                $ref: '#/components/schemas/Slot'          
        '405':
          description: Invalid input
      security:
        - bearerAuth: []
  
  /slots/all:
    get:
      tags:
        - slots
      summary: Lista a todos los materiales disponibles
      description: Devuelve a todos los materiales disponibles en la API. Requiere `slot_all`.
      operationId: allSlots
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Slot'          
        '400':
          description: Something went wrong
      security:
        - bearerAuth: []

components:
  schemas:

    Login:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
          example: admin@a.com
        password:
          type: string
          example: 1234
    
    NewPassword:
      required:
        - new_pass
      type: object
      properties:
        new_pass:
          type: string
          example: 123456
  
    Material:
      required:
        - name
        - price
        - arrivalDate
        - businessName
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Madera
        price:
          type: number
          format: float
          example: 1499.99
        arrivalDate:
          type: string
          format: date-time
          example: 2023-09-19 00:00:00
        businessName:
          type: string
          example: Maderera San Jorge
      xml:
        name: material
        
    Slot:
      required:
        - price
        - beginning
        - end
        - businessName
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        price:
          type: number
          format: float
          example: 84999.99
        beginning:
          type: string
          format: date-time
          example: 2023-09-19 00:00:00
        end:
          type: string
          format: date-time
          example: 2023-11-19 00:00:00
        businessName:
          type: string
          example: Ensambles Don Pepe
      xml:
        name: slot 
        
        
  requestBodies:
  
    materials:
      description: Materiales para agregar a la API
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Material'
        application/xml:
          schema:
            $ref: '#/components/schemas/Material'
    
    slots:
      description: Slots para agregar a la API
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Slot'
        application/xml:
          schema:
            $ref: '#/components/schemas/Slot'

  securitySchemes:
    #materialsslots_auth:
      #type: oauth2
      #flows:
        #implicit:
          #authorizationUrl: https://materialsslots3.swagger.io/oauth/authorize
          #scopes:
            #write:materials: modify materials in your account
            #read:materials: read your materials
            #write:slots: modify materials in your account
            #read:slots: read your materials
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []